package com.baeldung.springdoc.openapitools.models;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonSubTypes;
import com.fasterxml.jackson.annotation.JsonTypeInfo;


@JsonIgnoreProperties(
  value = "method", // ignore manually set method, it will be automatically generated by Jackson during serialization
  allowSetters = true // allows the method to be set during deserialization
)
@JsonTypeInfo(use = JsonTypeInfo.Id.NAME, include = JsonTypeInfo.As.PROPERTY, property = "method", visible = true)
@JsonSubTypes({
  @JsonSubTypes.Type(value = PollDeliveryMethod.class, name = "PollDeliveryMethod"),
  @JsonSubTypes.Type(value = PushDeliveryMethod.class, name = "PushDeliveryMethod")
})

public interface StreamConfigurationDelivery {
    public String getMethod();
}
